### PR TITLE
Proposal: Add optional typing to the SVID specification

### PR DESCRIPTION
**Pull request by ajessup**
This change describes adding typing to SVIDs, for cases where SVIDs correspond to real-world identities such as Kubernetes service accounts. When a type is specified and is one of the reserved types listed, the ID is expected to follow particular naming and issuing conventions.

### CODE REVIEW

**Comment by y2bishop2y** [comment]
So how does this differ from case version? Seems that we are encoding meaning into the String that we wanted to keep as a pristine identity.

**Comment by jbeda** [comment]
My gut reaction is to say that this is a bad idea.

Identity should be a pure concept.  There may be many mappings from k8s SAs to SPIFFE IDs (we may have a preferred way but it won't be the only way).  There are also other schemes that make sense for that.

If we want to map back from SPIFFE ID to SA, we should program clusters to do that mapping in the k8s authorizer.

Also note that I think the examples tend to paint a stricter picture than we probably want.  If I have staging and prod clusters for k8s, I may want:

`spiffe://staging.example.com/namespaces/my-ns/serviceaccounts/my-sa`

But I may also want to have:

`spiffe://example.com/staging/k8s/namespaces/my-ns/serviceaccounts/my-sa`

In the second case I can have a SPIFFE control plane that covers prod, staging and non-k8s workloads.  I'm not sure how the type proposed here would work in that case.

**Comment by jbeda** [comment]
(BTW -- if I'm slow to respond to this stuff please ping me on slack.  Github notifications tend to get lost with the deluge)

**Comment by ajessup** [comment]
Another concern raised by @rra offline - this format moves us from strcmp() to actually needing to parse the URI. And as per @y2bishop2y we also don't know if/how this will affect name constraints.

**Comment by ajessup** [comment]
Broadly, I think the consensus is that this approach (binding real-world identity in the SPIFFE name itself) is a bad idea. I'll close this PR, but raised the broader problem of mapping SVIDs to real world entities in #5.

**Pull request closed without merging**
